"use client";

import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Day = { id?: string; day_number: number; reference: string };
type Plan = { id:string; title:string; description:string|null; status:string; sort_order:number; reading_plan_days:Day[] };

const blank = { id:"", title:"", description:"", status:"draft", sort_order:100 };

export default function AdminPlanosLeituraPage(){
  const supabase=createClient();
  const [plans,setPlans]=useState<Plan[]>([]); const [form,setForm]=useState(blank); const [days,setDays]=useState<Day[]>([{day_number:1,reference:""}]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState("");
  async function load(){setLoading(true);setError("");const {data,error}=await supabase.from("reading_plan_catalog").select("id,title,description,status,sort_order,reading_plan_days(id,day_number,reference)").order("sort_order").order("created_at");if(error)setError(error.message||"Não foi possível carregar os planos.");setPlans((data||[]) as Plan[]);setLoading(false);}
  useEffect(()=>{void load();},[]);
  function edit(p:Plan){setForm({id:p.id,title:p.title,description:p.description||"",status:p.status,sort_order:p.sort_order});setDays([...(p.reading_plan_days||[])].sort((a,b)=>a.day_number-b.day_number));window.scrollTo({top:0,behavior:"smooth"});}
  function reset(){setForm(blank);setDays([{day_number:1,reference:""}]);}
  function addDay(){setDays(d=>[...d,{day_number:d.length+1,reference:""}]);}
  function removeDay(i:number){setDays(d=>d.filter((_,idx)=>idx!==i).map((x,idx)=>({...x,day_number:idx+1})));}
  async function save(e:FormEvent){e.preventDefault();setSaving(true);setError("");setMessage("");try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sessão administrativa inválida.");const clean=days.map((d,i)=>({day_number:i+1,reference:d.reference.trim()})).filter(d=>d.reference);if(!clean.length)throw new Error("Adicione pelo menos um dia de leitura.");let id=form.id;if(id){const {error:u}=await supabase.from("reading_plan_catalog").update({title:form.title.trim(),description:form.description.trim()||null,status:form.status,sort_order:Number(form.sort_order)||100,updated_at:new Date().toISOString(),...(form.status==="published"?{published_at:new Date().toISOString()}:{})}).eq("id",id);if(u)throw u;const {error:d}=await supabase.from("reading_plan_days").delete().eq("catalog_id",id);if(d)throw d;}else{const {data:p,error:i}=await supabase.from("reading_plan_catalog").insert({title:form.title.trim(),description:form.description.trim()||null,status:form.status,sort_order:Number(form.sort_order)||100,created_by:user.id,...(form.status==="published"?{published_at:new Date().toISOString()}:{})}).select("id").single();if(i)throw i;id=p.id;}
    const {error:di}=await supabase.from("reading_plan_days").insert(clean.map(d=>({catalog_id:id,day_number:d.day_number,reference:d.reference})));if(di)throw di;setMessage(form.id?"Plano atualizado.":"Plano criado.");reset();await load();}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar o plano.");}finally{setSaving(false);}}
  async function archive(p:Plan){const {error}=await supabase.from("reading_plan_catalog").update({status:"archived",updated_at:new Date().toISOString()}).eq("id",p.id);if(error)setError(error.message);else await load();}
  async function remove(p:Plan){if(!window.confirm("Remover este plano do catálogo? Usuários que já iniciaram manterão o progresso salvo."))return;const {error}=await supabase.from("reading_plan_catalog").delete().eq("id",p.id);if(error)setError(error.message);else{setMessage("Plano removido do catálogo. O progresso já iniciado foi preservado.");await load();}}
  return <main className="min-h-screen bg-[#F6F5F2] px-5 py-8 text-[#0F2131] lg:px-10"><div className="mx-auto max-w-6xl space-y-7"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#C4A47C]">CMS</p><h1 className="mt-2 font-serif text-3xl font-bold">Planos de leitura</h1><p className="mt-2 text-sm text-[#5E6E82]">Crie, publique, edite, arquive e remova planos sem perder o progresso dos usuários.</p></div><a href="/admin" className="rounded-xl border bg-white px-4 py-2 text-sm font-semibold">Voltar ao painel</a></header>{error&&<div className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}{message&&<div className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{message}</div>}
  <form onSubmit={save} className="space-y-5 rounded-2xl border bg-white p-6 shadow-sm"><div className="grid gap-4 md:grid-cols-2"><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="rounded-xl border px-4 py-3" placeholder="Título do plano"/><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="rounded-xl border px-4 py-3"><option value="draft">Rascunho</option><option value="published">Publicado</option><option value="archived">Arquivado</option></select><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={3} className="rounded-xl border px-4 py-3 md:col-span-2" placeholder="Descrição"/><input type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})} className="rounded-xl border px-4 py-3" placeholder="Ordem"/></div><div><div className="flex items-center justify-between"><h2 className="font-serif text-xl font-bold">Dias do plano</h2><button type="button" onClick={addDay} className="rounded-lg border px-3 py-2 text-xs font-semibold">+ Adicionar dia</button></div><div className="mt-3 space-y-2">{days.map((d,i)=><div key={i} className="flex gap-2"><span className="flex w-16 items-center justify-center rounded-xl bg-[#F6F5F2] text-sm font-semibold">Dia {i+1}</span><input required value={d.reference} onChange={e=>setDays(ds=>ds.map((x,idx)=>idx===i?{...x,reference:e.target.value}:x))} className="flex-1 rounded-xl border px-4 py-3" placeholder="Ex.: João 1:1-5"/>{days.length>1&&<button type="button" onClick={()=>removeDay(i)} className="rounded-xl border border-red-200 px-3 text-red-700">×</button>}</div>)}</div></div><div className="flex gap-2"><button disabled={saving} className="rounded-xl bg-[#8C183F] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{saving?"Salvando...":form.id?"Salvar alterações":"Criar plano"}</button>{form.id&&<button type="button" onClick={reset} className="rounded-xl border px-5 py-3 text-sm font-semibold">Cancelar edição</button>}</div></form>
  <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="font-serif text-2xl font-bold">Catálogo</h2>{loading?<p className="mt-4 text-sm">Carregando...</p>:<div className="mt-4 space-y-3">{plans.map(p=><article key={p.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border p-4"><div><p className="font-semibold">{p.title}</p><p className="mt-1 text-xs text-[#6A7885]">{p.status} · {(p.reading_plan_days||[]).length} dias · ordem {p.sort_order}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>edit(p)} className="rounded-lg border px-3 py-2 text-xs font-semibold">Editar</button>{p.status!=="archived"&&<button onClick={()=>archive(p)} className="rounded-lg border px-3 py-2 text-xs font-semibold">Arquivar</button>}<button onClick={()=>remove(p)} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-semibold text-red-700">Remover</button></div></article>)}{!plans.length&&<p className="text-sm text-[#6A7885]">Nenhum plano cadastrado.</p>}</div>}</section></div></main>;
}
