import Link from "next/link";
import { CoramLogo } from "../components/CoramLogo";

const benefits = [
  ["Estudos bíblicos profundos", "Pesquise passagens, personagens e temas com uma estrutura de estudo em 16 camadas."],
  ["Devocionais para a vida real", "Conteúdo para meditar, compreender e aplicar a Palavra no cotidiano."],
  ["Biblioteca cristã", "Um espaço organizado para conteúdos que apoiam sua caminhada e seu discipulado."],
  ["Sua jornada em um só lugar", "Salve estudos, favoritos, anotações e planos de leitura para continuar de onde parou."],
];

export default function PublicSite() {
  return <main className="min-h-screen bg-[#F8F9FA] text-[#0F2131]">
    <header className="border-b border-[#E1E7EA] bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><div className="rounded-xl bg-[#0F2131] px-4 py-3"><CoramLogo /></div><nav className="flex items-center gap-3"><Link href="/login" className="px-4 py-2 text-sm font-semibold">Entrar</Link><Link href="/assinatura" className="rounded-lg bg-[#8C183F] px-4 py-2.5 text-sm font-semibold text-white">Assinar</Link></nav></div></header>
    <section className="bg-[#0F2131] px-5 py-20 text-center text-white md:py-28"><div className="mx-auto max-w-4xl"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-[#C4A47C]">Uma vida diante de Deus</p><h1 className="mt-5 font-serif text-4xl font-bold leading-tight md:text-6xl">Aprofunde sua vida com Deus através da Palavra.</h1><p className="mx-auto mt-6 max-w-2xl text-base leading-8 text-white/70 md:text-lg">Coram Deo reúne estudo bíblico, devocionais e ferramentas de discipulado em uma experiência simples, organizada e feita para ajudar você a crescer com constância.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/assinatura" className="rounded-xl bg-[#8C183F] px-7 py-4 text-sm font-semibold">Começar minha jornada</Link><Link href="/login" className="rounded-xl border border-white/20 px-7 py-4 text-sm font-semibold">Já sou aluno</Link></div></div></section>
    <section className="mx-auto max-w-6xl px-5 py-16 md:py-20"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#8C183F]">Coram Deo</p><h2 className="mt-3 font-serif text-3xl font-bold md:text-4xl">Mais profundidade. Menos distração.</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-[#5E6E82]">Ferramentas pensadas para servir à sua caminhada cristã — não para substituir a Bíblia, a igreja local ou o discipulado.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2">{benefits.map(([title, description], index) => <article key={title} className="rounded-2xl border border-[#E1E7EA] bg-white p-7"><span className="text-sm font-bold text-[#C4A47C]">0{index+1}</span><h3 className="mt-3 font-serif text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#5E6E82]">{description}</p></article>)}</div></section>
    <section className="bg-white px-5 py-16 md:py-20"><div className="mx-auto grid max-w-6xl items-center gap-10 md:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#C4A47C]">Estude com profundidade</p><h2 className="mt-3 font-serif text-3xl font-bold">Da pergunta à compreensão.</h2><p className="mt-4 leading-7 text-[#5E6E82]">O motor de pesquisa bíblica do Coram Deo organiza o estudo em camadas de evidência, interpretação e tradição, com diferentes modos de aprofundamento. A tecnologia serve ao estudo; a Palavra permanece no centro.</p></div><div className="rounded-2xl bg-[#0F2131] p-8 text-white"><p className="text-xs font-semibold uppercase tracking-widest text-[#C4A47C]">Sua jornada</p><p className="mt-5 font-serif text-2xl font-bold">Pesquisar → compreender → anotar → continuar</p><p className="mt-4 text-sm leading-7 text-white/65">Seus estudos e anotações ficam organizados para que sua caminhada não termine quando você fecha a página.</p></div></div></section>
    <section className="px-5 py-16 text-center md:py-20"><div className="mx-auto max-w-3xl rounded-3xl bg-[#8C183F] px-7 py-12 text-white"><p className="text-sm font-semibold text-white/70">Plano Coram Deo</p><p className="mt-3 font-serif text-4xl font-bold">R$ 24,99 <span className="text-base font-normal text-white/70">/ mês</span></p><p className="mx-auto mt-4 max-w-xl text-sm leading-6 text-white/75">Acesso aos recursos da V1. A assinatura é processada pela Kiwify.</p><Link href="/assinatura" className="mt-7 inline-block rounded-xl bg-white px-7 py-4 text-sm font-bold text-[#8C183F]">Assinar o Coram Deo</Link></div></section>
    <footer className="border-t border-[#E1E7EA] bg-white px-5 py-8"><div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-4 text-xs text-[#5E6E82] sm:flex-row"><p>© 2026 Coram Deo. Uma vida diante de Deus.</p><div className="flex gap-5"><Link href="/termos">Termos de Uso</Link><Link href="/privacidade">Privacidade</Link><Link href="/login">Entrar</Link></div></div></footer>
  </main>;
}
