export default function PrivacidadePage() {
  return (
    <main className="min-h-screen bg-[#F7F4EF] px-5 py-12 text-[#0F2131]">
      <article className="mx-auto max-w-3xl rounded-2xl bg-white p-7 shadow-sm sm:p-10">
        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#8C183F]">Coram Deo</p>
        <h1 className="mt-3 font-serif text-3xl font-bold">Política de Privacidade</h1>
        <p className="mt-2 text-sm text-[#5E6E82]">Versão 1.0 · vigência a partir de 11 de setembro de 2026</p>
        <div className="mt-8 space-y-7 text-sm leading-7 text-[#334155]">
          <section><h2 className="font-semibold text-[#0F2131]">1. Objetivo</h2><p>Esta Política explica como o Coram Deo trata dados pessoais para operar contas, personalizar a experiência, armazenar estudos e materiais, disponibilizar recursos de inteligência artificial, oferecer suporte e administrar assinaturas.</p></section>
          <section><h2 className="font-semibold text-[#0F2131]">2. Responsável e contato</h2><p>Responsável pelo serviço: Dirceu José Gonzaga Junior. Para assuntos de privacidade, suporte ou exercício de direitos, entre em contato pelo e-mail contato@jesuscopybh.com.br. O aplicativo está disponível inicialmente em https://coram-deo-beta-public.vercel.app.</p></section>
          <section><h2 className="font-semibold text-[#0F2131]">3. Dados tratados</h2><p>Podemos tratar nome, e-mail, identificadores de conta, preferências de estudo, estudos salvos, notas, favoritos, progresso em planos, materiais criados, dados técnicos necessários à segurança e diagnóstico, feedbacks e informações relacionadas ao status da assinatura. Dados completos de cartão não são armazenados pelo Coram Deo quando o pagamento é processado pela Kiwify.</p></section>
          <section><h2 className="font-semibold text-[#0F2131]">4. Finalidades</h2><p>Os dados são utilizados para autenticação e segurança, funcionamento e personalização do serviço, sincronização dos recursos do usuário, geração de conteúdos solicitados, prevenção de abuso e fraude, diagnóstico de falhas, suporte, gestão de acesso e assinatura, cumprimento de obrigações legais e melhoria do produto.</p></section>
          <section><h2 className="font-semibold text-[#0F2131]">5. Inteligência artificial e fornecedores</h2><p>Solicitações necessárias à geração de estudos e materiais podem ser processadas por provedores tecnológicos utilizados pelo Coram Deo. Buscamos minimizar o envio de dados pessoais desnecessários. A infraestrutura também utiliza serviços especializados para banco de dados, autenticação, hospedagem e pagamentos.</p></section>
          <section><h2 className="font-semibold text-[#0F2131]">6. Infraestrutura e compartilhamento</h2><p>O Coram Deo utiliza Supabase para recursos de banco de dados e autenticação, Vercel para hospedagem da aplicação e Kiwify para o fluxo de pagamento. Dados são compartilhados com fornecedores somente na medida necessária à prestação das respectivas funções, observadas as condições e políticas aplicáveis.</p></section>
          <section><h2 className="font-semibold text-[#0F2131]">7. Links e conteúdos externos</h2><p>Ao acessar links, vídeos ou serviços de terceiros, o usuário passa a estar sujeito às políticas e práticas desses serviços externos.</p></section>
          <section><h2 className="font-semibold text-[#0F2131]">8. Bases legais</h2><p>O tratamento é realizado conforme hipóteses previstas na legislação brasileira aplicável, incluindo execução do serviço solicitado ou contratado, cumprimento de obrigações legais, exercício regular de direitos, legítimos interesses quando cabíveis e consentimento quando necessário.</p></section>
          <section><h2 className="font-semibold text-[#0F2131]">9. Retenção e exclusão</h2><p>Os dados são mantidos pelo período necessário às finalidades do serviço e às obrigações legais, de segurança e defesa de direitos. Solicitações de exclusão serão atendidas quando aplicáveis, ressalvadas hipóteses legítimas de conservação.</p></section>
          <section><h2 className="font-semibold text-[#0F2131]">10. Direitos do titular</h2><p>Nos termos da LGPD, o titular pode exercer os direitos previstos em lei, incluindo confirmação e acesso, correção, informações sobre compartilhamento e, quando cabível, anonimização, bloqueio, eliminação, portabilidade, oposição e revogação de consentimento. Solicitações podem ser encaminhadas para contato@jesuscopybh.com.br.</p></section>
          <section><h2 className="font-semibold text-[#0F2131]">11. Segurança</h2><p>Adotamos medidas técnicas e organizacionais destinadas a reduzir riscos de acesso não autorizado, perda, alteração ou divulgação indevida. Nenhum sistema é totalmente imune a incidentes e, quando necessário, serão adotadas medidas de resposta compatíveis com a legislação.</p></section>
          <section><h2 className="font-semibold text-[#0F2131]">12. Crianças e adolescentes</h2><p>A V1 do Coram Deo não é direcionada especificamente a crianças. Caso o tratamento de dados de crianças ou adolescentes seja identificado ou venha a fazer parte de uma oferta específica, serão observadas as exigências legais aplicáveis e as medidas adequadas ao melhor interesse desse público.</p></section>
          <section><h2 className="font-semibold text-[#0F2131]">13. Alterações</h2><p>Esta Política pode ser atualizada para refletir mudanças no serviço ou requisitos legais. Alterações materiais serão comunicadas de forma adequada e a versão vigente permanecerá identificada nesta página.</p></section>
        </div>
      </article>
    </main>
  )
}
